(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.GarminParser=api;})(typeof window!=="undefined"?window:globalThis,function(){
"use strict";
const MONTHS={ene:"ene",feb:"feb",mar:"mar",abr:"abr",may:"may",jun:"jun",jul:"jul",ago:"ago",sep:"sep",sept:"sep",oct:"oct",nov:"nov",dic:"dic"};
const RESERVED=["carrera","resumen","estadisticas","vueltas","graficos","equipo","anadir notas","distancia","tiempo","ritmo","frecuencia cardiaca","cadencia","calorias","temperatura","desnivel","ascenso","descenso","entrenamiento","training effect","stamina","mapa"];
const ACTIVITIES=["rodaje","series","intervalos","tempo","tirada larga","recuperacion","carrera","trail","running","calentamiento","enfriamiento"];
const cleanText=x=>String(x||"").replace(/\r/g,"\n").replace(/[‐‑‒–—]/g,"-").replace(/[“”]/g,'"').replace(/[’]/g,"'").replace(/\u00a0/g," ").replace(/[ \t]+/g," ").replace(/\n{3,}/g,"\n\n").trim();
const normalize=x=>cleanText(x).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const linesOf=x=>cleanText(x).split("\n").map(s=>s.trim()).filter(Boolean);
const num=x=>{if(x==null)return null;const n=Number(String(x).replace(",",".").replace(/[^0-9.\-]/g,""));return Number.isFinite(n)?n:null};
const pace=x=>{const m=String(x||"").match(/\b([0-9]{1,2})\s*[:.]\s*([0-5][0-9])\b/);if(!m)return null;const min=Number(m[1]);return min>=2&&min<=20?`${min}:${m[2]}`:null};
const duration=x=>{const s=String(x||"");let m=s.match(/\b([0-9]{1,2}):([0-5][0-9]):([0-5][0-9])\b/);if(m)return`${Number(m[1])}:${m[2]}:${m[3]}`;m=s.match(/\b([0-9]{1,3}):([0-5][0-9])\b/);return m?`${Number(m[1])}:${m[2]}`:null};
const field=(value,source,confidence,reason="")=>value==null?{value:null,source:null,confidence:0,reason}:{value,source,confidence,reason};
function around(lines,labelRegex,valueRegex,radius=2){for(let i=0;i<lines.length;i++){if(!labelRegex.test(normalize(lines[i])))continue;for(let d=0;d<=radius;d++){for(const j of d?[i-d,i+d]:[i]){if(j<0||j>=lines.length)continue;const match=lines[j].match(valueRegex);if(match)return{match,source:lines[j],label:lines[i],index:i}}}}return null}
function badTitle(line){const n=normalize(line).replace(/^[<>\-:|]+/,"").trim();if(!n||n.length<4||n.length>70)return true;if(RESERVED.some(w=>n===w||n.startsWith(w+" ")))return true;if(/^[0-9:.,/ %°a-z]{1,14}$/i.test(n)&&/\d/.test(n))return true;if(/^(<|>|menu|atras|mas|editar)/i.test(n))return true;return false}
function detectTitle(lines){const c=[];lines.forEach((line,index)=>{if(badTitle(line))return;const n=normalize(line);let score=0;if(/\s-\s/.test(line))score+=5;if(ACTIVITIES.some(w=>n.includes(w)))score+=3;if(/[a-záéíóúñ]{4,}/i.test(line))score++;if(index<18)score++;if(/[<>|]/.test(line))score-=6;c.push({line:line.replace(/^[<>\s]+/,"").replace(/[|]+$/,"").trim(),score,index})});return(c.sort((a,b)=>b.score-a.score||a.index-b.index).find(x=>x.score>=5)||{}).line||null}
function splitTitle(title){if(!title)return{location:null,activity:null};const p=title.split(/\s+-\s+/).map(s=>s.trim()).filter(Boolean);if(p.length>=2)return{location:p[0],activity:p.slice(1).join(" - ")};const n=normalize(title);return{location:null,activity:ACTIVITIES.some(w=>n.includes(w))?title:null}}
function detectDate(raw){let m=raw.match(/\b([0-3]?[0-9])\s+(ene|feb|mar|abr|may|jun|jul|ago|sep|sept|oct|nov|dic)(?:\.|\s)?(?:\s+(20[0-9]{2}))?\b/i);if(m)return{value:`${Number(m[1])} ${MONTHS[normalize(m[2]).replace(".","")]||m[2].toLowerCase()}${m[3]?" "+m[3]:""}`,source:m[0],confidence:.97};m=raw.match(/\b([0-3]?[0-9])[\/.\-]([0-1]?[0-9])[\/.\-](20[0-9]{2})\b/);return m?{value:`${String(Number(m[1])).padStart(2,"0")}/${String(Number(m[2])).padStart(2,"0")}/${m[3]}`,source:m[0],confidence:.98}:null}
function parse(text){const raw=cleanText(text),norm=normalize(raw),lines=linesOf(raw);
const dist=around(lines,/\bdistancia\b/,/\b([0-9]{1,3}(?:[,.][0-9]{1,2})?)\s*(?:km)?\b/i,3);let distance=dist?num(dist.match[1]):null;if(distance!=null&&(distance<.1||distance>300))distance=null;
const avg=around(lines,/frecuencia cardiaca media|fc media|pulso medio/,/\b([4-9][0-9]|1[0-9]{2}|2[0-3][0-9])\s*(?:ppm|bpm)?\b/i,3);
const max=around(lines,/frecuencia cardiaca maxima|fc maxima|pulso maximo/,/\b([5-9][0-9]|1[0-9]{2}|2[0-4][0-9])\s*(?:ppm|bpm)?\b/i,3);
const pc=around(lines,/ritmo medio|ritmo promedio/,/\b([0-9]{1,2}\s*[:.]\s*[0-5][0-9])\s*(?:\/\s*km|km)?\b/i,3);const avgPace=pc?pace(pc.match[1]):null;
const tc=around(lines,/tiempo total|duracion|tiempo transcurrido/,/\b(?:[0-9]{1,2}:)?[0-9]{1,3}:[0-5][0-9]\b/,3);let totalTime=tc?duration(tc.match[0]):null;if(totalTime===avgPace)totalTime=null;
const cal=around(lines,/calorias totales|calorias/,/\b([0-9]{2,5})\s*(?:kcal|cal)?\b/i,2);let calories=cal?num(cal.match[1]):null;if(calories!=null&&(calories<10||calories>10000))calories=null;
const cad=around(lines,/cadencia media|cadencia promedio|cadencia/,/\b([8-9][0-9]|1[0-9]{2}|2[0-4][0-9])\s*(?:ppm|spm|pasos\/min)?\b/i,3);
const temp=around(lines,/temperatura media|temperatura/,/\b(-?[0-9]{1,2}(?:[,.][0-9])?)\s*°?\s*c\b/i,3);
const elev=around(lines,/desnivel positivo|ascenso total|ganancia de altura|elevacion/,/\b([0-9]{1,5})\s*m\b/i,3);
const date=detectDate(raw),title=detectTitle(lines),parts=splitTitle(title);
const clocks=[...raw.matchAll(/\b([0-2]?[0-9]):([0-5][0-9])\b/g)].map(m=>({value:`${String(Number(m[1])).padStart(2,"0")}:${m[2]}`,source:m[0],index:m.index})).filter(x=>x.value!==avgPace&&x.value!==totalTime);const clock=clocks.find(x=>x.index<Math.max(180,raw.length*.25))||clocks[0]||null;
const fields={source:field(/garmin|garmin connect|resumen\s+estadisticas\s+vueltas/i.test(norm)?"Garmin":"Garmin probable","Diseño/texto detectado",.82),title:field(title,title,title?.includes(" - ")?.96:title?.9:0),location:field(parts.location,title,parts.location?.93:0),activity:field(parts.activity,title,parts.activity?.93:0),date:field(date?.value||null,date?.source||null,date?.confidence||0),time:field(clock?.value||null,clock?.source||null,clock?.68:0),distance_km:field(distance,dist?.source,distance!=null?.97:0),avg_heart_rate_bpm:field(avg?num(avg.match[1]):null,avg?.source,avg?.98:0),max_heart_rate_bpm:field(max?num(max.match[1]):null,max?.source,max?.98:0),avg_pace_min_km:field(avgPace,pc?.source,avgPace?.98:0),total_time:field(totalTime,tc?.source,totalTime?.94:0),calories_kcal:field(calories,cal?.source,calories!=null?.88:0),cadence_spm:field(cad?num(cad.match[1]):null,cad?.source,cad?.94:0),temperature_c:field(temp?num(temp.match[1]):null,temp?.source,temp?.94:0),elevation_gain_m:field(elev?num(elev.match[1]):null,elev?.source,elev?.93:0)};
const data=Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value]));const warnings=[];if(fields.time.value&&!date)warnings.push("La hora se ha detectado sin fecha y conviene revisarla.");if(calories!=null&&distance!=null&&calories<distance*20)warnings.push("Las calorías parecen demasiado bajas para la distancia.");if(fields.avg_heart_rate_bpm.value&&fields.max_heart_rate_bpm.value&&fields.max_heart_rate_bpm.value<fields.avg_heart_rate_bpm.value)warnings.push("La FC máxima es inferior a la media.");return{parser:"garmin-v2.5.0",found:Object.values(fields).filter(x=>x.value!=null).length,data,fields,warnings,raw_text:raw}}
function merge(results){const keys=["source","title","location","activity","date","time","distance_km","avg_heart_rate_bpm","max_heart_rate_bpm","avg_pace_min_km","total_time","calories_kcal","cadence_spm","temperature_c","elevation_gain_m"],fields={};for(const key of keys){const c=[];results.forEach((r,i)=>{const x=r.fields[key];if(x?.value!=null)c.push({...x,capture:i+1})});if(!c.length){fields[key]=field(null,null,0);continue}if(["title","location","activity","date","time"].includes(key)){const g=new Map();for(const x of c){const k=normalize(x.value),v=g.get(k)||{best:x,count:0,total:0};v.count++;v.total+=x.confidence;if(x.confidence>v.best.confidence)v.best=x;g.set(k,v)}const w=[...g.values()].sort((a,b)=>(b.count*2+b.total)-(a.count*2+a.total))[0];fields[key]={...w.best,confidence:Math.min(.99,w.best.confidence+(w.count-1)*.03),reason:`Consenso de ${w.count} captura(s)`}}else fields[key]=c.sort((a,b)=>b.confidence-a.confidence)[0]}
const data=Object.fromEntries(keys.map(k=>[k,fields[k].value]));const warnings=[...new Set(results.flatMap(r=>r.warnings||[]))];if(data.calories_kcal!=null&&data.distance_km!=null&&data.calories_kcal<data.distance_km*20)warnings.push("Revisa las calorías: el valor fusionado parece bajo para la distancia.");if(data.time&&data.avg_pace_min_km&&data.time===data.avg_pace_min_km)warnings.push("La hora coincide con el ritmo; puede ser una lectura errónea.");if(data.title&&/^[<>]/.test(data.title))warnings.push("El título todavía contiene un símbolo de navegación.");return{parser:"garmin-v2.5.0-merge",found:Object.values(data).filter(v=>v!=null).length,data,fields,warnings}}
return{parse,merge,cleanText,normalize};
});
